// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edqeymtqmgegudwcnzfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkcWV5bXRxbWdlZ3Vkd2NuemZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzQxNDMsImV4cCI6MjA3NDIxMDE0M30.vbjCkJg_kVm50MzyjP_u9qWvDvIm41g7d9TET4EfXpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});