// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://errbigvlfplhispjzily.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVycmJpZ3ZsZnBsaGlzcGp6aWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NDc5OTUsImV4cCI6MjA4NjEyMzk5NX0.IQR0H-Gq0JDoRPTU7nZwSuRkF1EcrniUXgW-0lHGQis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});